export enum NotificationKind {
  INVITATION_SENT = 'INVITATION_SENT',
  REGISTRATION_CONFIRMED = 'REGISTRATION_CONFIRMED',
  REVIEW_SUBMITTED = 'REVIEW_SUBMITTED',
  REVIEW_RETURNED = 'REVIEW_RETURNED',
  PORTFOLIO_BATCH_COMPLETED = 'PORTFOLIO_BATCH_COMPLETED',
  REVIEWER_ASSIGNED = 'REVIEWER_ASSIGNED',
}
